# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

base_path:
    path: /
    controller: App\Controller\BrandingController::index
    methods: [GET]

portfolio:
    path: /portfolio
    controller: App\Controller\BrandingController::portfolio
    methods: [GET]

services:
    path: /services
    controller: App\Controller\BrandingController::services
    methods: [GET]

contact-us:
    path: /contact-us
    controller: App\Controller\BrandingController::contactUs
    methods: [GET]